language: go
services:
  - memcache # github.com/robfig/revel/cache
install:
  - find .
  - go get -d -v github.com/robfig/revel/...
script:
  - go test github.com/robfig/revel
  - go test github.com/robfig/revel/cache
  - go test github.com/robfig/revel/harness

  # Build the command line tool
  - go build -o $GOPATH/bin/revel github.com/robfig/revel/cmd

  # Ensure the new-app flow works (plus the other commands).
  - $GOPATH/bin/revel new     my/testapp
  - $GOPATH/bin/revel test    my/testapp
  - $GOPATH/bin/revel clean   my/testapp
  - $GOPATH/bin/revel build   my/testapp $TMP/testapp
  - $GOPATH/bin/revel package my/testapp

  # Build & run the sample apps
  - $GOPATH/bin/revel test github.com/robfig/revel/samples/booking
  - $GOPATH/bin/revel test github.com/robfig/revel/samples/chat
  - $GOPATH/bin/revel test github.com/robfig/revel/samples/facebook-oauth2
  - $GOPATH/bin/revel test github.com/robfig/revel/samples/twitter-oauth
  - $GOPATH/bin/revel test github.com/robfig/revel/samples/validation
  - $GOPATH/bin/revel test github.com/robfig/revel/samples/chat

