language: go
services:
  - memcache # github.com/robfig/revel/cache
install:
  - go get -d -v github.com/robfig/revel
  - go get -d -v github.com/robfig/revel/cache
  - go get -d -v github.com/robfig/revel/cmd
  - go get -d -v github.com/robfig/revel/harness
script:
  - go test github.com/robfig/revel
  - go test github.com/robfig/revel/cache
  - go test github.com/robfig/revel/harness
  - go build github.com/robfig/revel/cmd
  
# TODO: Add sample app testing
